### ISSUE TITLE
[DEV - BDD] : Développer la conception du MCD

### ISSUE THREAD

**Issue by GaelSimon01** [stevenMarmion/sae-web-php#1]
Le but de cet issues est de concevoir le MCD, pour l'application WEB PHP

**Comment by stevenMarmion** [comment]
La PR a été review et validée, nous pouvons close cette issue

**Comment by stevenMarmion** [comment]
Nous réouvrons l'issue puisqu'il y a eu une erreur dans l'analyse du jeu de données. Ce sont des albums et non musqiues et un album à une liste de genre

**Comment by stevenMarmion** [comment]
Le MCD est bon, nous réouvrirons l'issue si des erreurs sont survenus ou que nous devons entrer dans un nouveau versionnage de l'appli avec de nouvelles tables
