### ISSUE TITLE
[DEV - ROUTE] : Développer la protection des routes

### ISSUE THREAD

**Issue by stevenMarmion** [stevenMarmion/sae-web-php#55]
Cette issue concerne n'importe quel protection de chemin : 

Si l'utilisateur veut accéder au site en tapant une URL sans être connecté ==> le faire venir à la page de connexion / inscription
Si l'utilisateur tape l'URL du panel admin sans être admin ==> lui mettre un message de warning et le prévenant qu'il n'a pas accès à cette partie de l'application et lui mettre à disposition un bouton qui le fait revenir en lieu sûr

**Comment by DepontSamuel** [comment]
La pr vient d'etre fait donc je faire l'issue
