### ISSUE TITLE
[DEV - INTERFACE] : Developper la pagination de la page d'accueil

### ISSUE THREAD

**Issue by GaelSimon01** [stevenMarmion/sae-web-php#63]
le but et de développer la fonctionnalité de pagination dans la page d'accueil pour éviter d'avoir tout les albums sur une seul page

**Comment by stevenMarmion** [comment]
La PR associée à l'issue vient d'être review et merge, nous pouvons close l'issue tant qu'il n'y a pas de nouveau changement à faire

**Comment by stevenMarmion** [comment]
Nous réouvrons l'issue pour changer le style des boutons, de plus le changement concernera : 

- La modification de la nomenclature des boutons
- La mise en place des boutons dans la page

**Comment by stevenMarmion** [comment]
La nouvelle PR associée au style des boutons vient d'être review et merge, nous pouvons close l'issue

**Comment by stevenMarmion** [comment]
Nous réouvrons cette issue car nous devons ajouter la disponibilité de savoir dans quel page nous sommes, pour cela : 

- Afficher la page actuelle entre le bouton précédent et suivant 
- Afficher la pagniation en haut et en bas de page

**Comment by stevenMarmion** [comment]
La nouvelle PR associée au à la remise en forme de la pagination vient d'être review et merge, nous pouvons close l'issue

**Comment by stevenMarmion** [comment]
Nous réouvrons cette issue car nous devons implémenter la chose suivante : 

- Si nous sommes arrivés à la page maximal, désactiver le bouton associé à la page suivante

Dans la même principe : implémenter la même chose pour le bouton de la page précédente

**Comment by stevenMarmion** [comment]
La PR concernant les implémentations des cliques boutons sur la pagination vient d'être review et merge, nous pouvons close cette issue désormai
